---
abstract: 'Edit and validate LcdProc configuration file'
author:
  - 'Dominique Dumont'
build_requires:
  File::Copy::Recursive: 0
  File::Slurp: 0
  Module::Build: 0.34
  Path::Class: 0
  Test::Differences: 0
  Test::Exception: 0
  Test::File::Contents: 0
  Test::Memory::Cycle: 0
  Test::More: 0
  Test::Warn: 0.11
configure_requires:
  Module::Build: 0.34
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.008, CPAN::Meta::Converter version 2.133380'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Model-LcdProc
requires:
  Config::Model: 2.043
  Exception::Class: 0
  Log::Log4perl: 1.11
  Mouse: 0
  MouseX::NativeTraits: 0
  perl: v5.10.1
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Config-Model-LcdProc
  homepage: https://github.com/dod38fr/config-model/wiki
  repository: git://github.com/dod38fr/config-model-lcdproc.git
version: 2.041
