---
abstract: 'Edit and validate LcdProc configuration file'
author:
  - 'Dominique Dumont'
build_requires:
  Config::Model::Tester: '0'
  Module::Build: '0.34'
configure_requires:
  Config::Model: '0'
  Config::Model::Backend::IniFile: '0'
  Config::Model::Itself: '1.240'
  Getopt::Long: '0'
  IO::File: '0'
  IO::String: '0'
  Log::Log4perl: '0'
  Module::Build: '0.34'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141170'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Model-LcdProc
requires:
  Config::Model: '2.043'
  perl: '5.010'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Config-Model-LcdProc
  homepage: https://github.com/dod38fr/config-model/wiki
  repository: git://github.com/dod38fr/config-model-lcdproc.git
version: '2.042'
